/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/xule/vuepress/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-73453928",
    path: "/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73453928").then(next)
    },
  },
  {
    name: "v-5d81d274",
    path: "/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d81d274").then(next)
    },
  },
  {
    name: "v-3c48d225",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c48d225").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-21d2ac23",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21d2ac23").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-d5771bce",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d5771bce").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-09c23cc8",
    path: "/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09c23cc8").then(next)
    },
  },
  {
    name: "v-8e1ab568",
    path: "/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8e1ab568").then(next)
    },
  },
  {
    name: "v-263a0700",
    path: "/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-263a0700").then(next)
    },
  },
  {
    name: "v-38f82170",
    path: "/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-38f82170").then(next)
    },
  },
  {
    name: "v-32d45ae8",
    path: "/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32d45ae8").then(next)
    },
  },
  {
    name: "v-411d91a8",
    path: "/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-411d91a8").then(next)
    },
  },
  {
    name: "v-1def10c8",
    path: "/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1def10c8").then(next)
    },
  },
  {
    name: "v-32196c68",
    path: "/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32196c68").then(next)
    },
  },
  {
    name: "v-8150c4dc",
    path: "/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8150c4dc").then(next)
    },
  },
  {
    name: "v-af314a20",
    path: "/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af314a20").then(next)
    },
  },
  {
    name: "v-4dc37c88",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dc37c88").then(next)
    },
  },
  {
    name: "v-994d2284",
    path: "/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-994d2284").then(next)
    },
  },
  {
    name: "v-410b8f01",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-410b8f01").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6b3ec228",
    path: "/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b3ec228").then(next)
    },
  },
  {
    name: "v-5ec9ab14",
    path: "/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ec9ab14").then(next)
    },
  },
  {
    name: "v-0f964348",
    path: "/miscellaneous/local-development.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f964348").then(next)
    },
  },
  {
    name: "v-c6511c70",
    path: "/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c6511c70").then(next)
    },
  },
  {
    name: "v-14317003",
    path: "/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14317003").then(next)
    },
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-175d40f4",
    path: "/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-175d40f4").then(next)
    },
  },
  {
    name: "v-40b442b0",
    path: "/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40b442b0").then(next)
    },
  },
  {
    name: "v-2e976786",
    path: "/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e976786").then(next)
    },
  },
  {
    name: "v-71567518",
    path: "/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71567518").then(next)
    },
  },
  {
    name: "v-25663e70",
    path: "/plugin/official/plugin-blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25663e70").then(next)
    },
  },
  {
    name: "v-2dfe26c8",
    path: "/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2dfe26c8").then(next)
    },
  },
  {
    name: "v-2924e9f0",
    path: "/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2924e9f0").then(next)
    },
  },
  {
    name: "v-722ca282",
    path: "/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-722ca282").then(next)
    },
  },
  {
    name: "v-f8b47738",
    path: "/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f8b47738").then(next)
    },
  },
  {
    name: "v-aa74ab3c",
    path: "/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa74ab3c").then(next)
    },
  },
  {
    name: "v-c163e850",
    path: "/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c163e850").then(next)
    },
  },
  {
    name: "v-905043f0",
    path: "/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-905043f0").then(next)
    },
  },
  {
    name: "v-64e466f0",
    path: "/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64e466f0").then(next)
    },
  },
  {
    name: "v-66baf8c8",
    path: "/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66baf8c8").then(next)
    },
  },
  {
    name: "v-359e33c8",
    path: "/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-359e33c8").then(next)
    },
  },
  {
    name: "v-7836a9bf",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7836a9bf").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-2d4a2f28",
    path: "/theme/blog-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d4a2f28").then(next)
    },
  },
  {
    name: "v-245d0084",
    path: "/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-245d0084").then(next)
    },
  },
  {
    name: "v-99b66e70",
    path: "/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-99b66e70").then(next)
    },
  },
  {
    name: "v-8bc734b8",
    path: "/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8bc734b8").then(next)
    },
  },
  {
    name: "v-7edc83f0",
    path: "/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7edc83f0").then(next)
    },
  },
  {
    name: "v-5a6f8a88",
    path: "/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a6f8a88").then(next)
    },
  },
  {
    name: "v-666b1d23",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-666b1d23").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    name: "v-13647ba0",
    path: "/zh/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13647ba0").then(next)
    },
  },
  {
    name: "v-a2111570",
    path: "/zh/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a2111570").then(next)
    },
  },
  {
    name: "v-1fc5904b",
    path: "/zh/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fc5904b").then(next)
    },
  },
  {
    path: "/zh/config/index.html",
    redirect: "/zh/config/"
  },
  {
    name: "v-0320befa",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0320befa").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    name: "v-209103c3",
    path: "/zh/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-209103c3").then(next)
    },
  },
  {
    path: "/zh/faq/index.html",
    redirect: "/zh/faq/"
  },
  {
    name: "v-5680bda8",
    path: "/zh/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5680bda8").then(next)
    },
  },
  {
    name: "v-d6f6e0b0",
    path: "/zh/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d6f6e0b0").then(next)
    },
  },
  {
    name: "v-63929028",
    path: "/zh/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63929028").then(next)
    },
  },
  {
    name: "v-bb8d2e70",
    path: "/zh/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bb8d2e70").then(next)
    },
  },
  {
    name: "v-59102394",
    path: "/zh/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59102394").then(next)
    },
  },
  {
    name: "v-01e8eea8",
    path: "/zh/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01e8eea8").then(next)
    },
  },
  {
    name: "v-41132dee",
    path: "/zh/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41132dee").then(next)
    },
  },
  {
    name: "v-e247f1f0",
    path: "/zh/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e247f1f0").then(next)
    },
  },
  {
    name: "v-0fbb8d38",
    path: "/zh/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fbb8d38").then(next)
    },
  },
  {
    name: "v-51584b68",
    path: "/zh/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51584b68").then(next)
    },
  },
  {
    name: "v-4a237dc8",
    path: "/zh/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a237dc8").then(next)
    },
  },
  {
    name: "v-db7effbc",
    path: "/zh/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db7effbc").then(next)
    },
  },
  {
    name: "v-03ff2544",
    path: "/zh/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03ff2544").then(next)
    },
  },
  {
    name: "v-629d8906",
    path: "/zh/miscellaneous/local-development.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-629d8906").then(next)
    },
  },
  {
    name: "v-008ba970",
    path: "/zh/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-008ba970").then(next)
    },
  },
  {
    name: "v-1e0d7b04",
    path: "/zh/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e0d7b04").then(next)
    },
  },
  {
    name: "v-156e71ae",
    path: "/zh/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-156e71ae").then(next)
    },
  },
  {
    path: "/zh/plugin/index.html",
    redirect: "/zh/plugin/"
  },
  {
    name: "v-c16013b0",
    path: "/zh/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c16013b0").then(next)
    },
  },
  {
    name: "v-ccb33fd8",
    path: "/zh/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ccb33fd8").then(next)
    },
  },
  {
    name: "v-60720370",
    path: "/zh/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60720370").then(next)
    },
  },
  {
    name: "v-0f63a530",
    path: "/zh/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f63a530").then(next)
    },
  },
  {
    name: "v-7a9f680e",
    path: "/zh/plugin/official/plugin-blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a9f680e").then(next)
    },
  },
  {
    name: "v-fe11c624",
    path: "/zh/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe11c624").then(next)
    },
  },
  {
    name: "v-9114df6c",
    path: "/zh/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9114df6c").then(next)
    },
  },
  {
    name: "v-e5c827f0",
    path: "/zh/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e5c827f0").then(next)
    },
  },
  {
    name: "v-240d2588",
    path: "/zh/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-240d2588").then(next)
    },
  },
  {
    name: "v-024ec828",
    path: "/zh/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-024ec828").then(next)
    },
  },
  {
    name: "v-ba834d30",
    path: "/zh/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba834d30").then(next)
    },
  },
  {
    name: "v-456df90c",
    path: "/zh/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-456df90c").then(next)
    },
  },
  {
    name: "v-1fad9fc2",
    path: "/zh/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fad9fc2").then(next)
    },
  },
  {
    name: "v-7f65df24",
    path: "/zh/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f65df24").then(next)
    },
  },
  {
    name: "v-32270544",
    path: "/zh/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32270544").then(next)
    },
  },
  {
    name: "v-df9adcba",
    path: "/zh/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df9adcba").then(next)
    },
  },
  {
    path: "/zh/theme/index.html",
    redirect: "/zh/theme/"
  },
  {
    name: "v-26f723e8",
    path: "/zh/theme/blog-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26f723e8").then(next)
    },
  },
  {
    name: "v-7c12ebb0",
    path: "/zh/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c12ebb0").then(next)
    },
  },
  {
    name: "v-51e8742e",
    path: "/zh/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51e8742e").then(next)
    },
  },
  {
    name: "v-e739d730",
    path: "/zh/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e739d730").then(next)
    },
  },
  {
    name: "v-2594b9da",
    path: "/zh/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2594b9da").then(next)
    },
  },
  {
    name: "v-3e75e6ea",
    path: "/zh/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e75e6ea").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]